### PR TITLE
Add compatibility for asynctest

### PR DESCRIPTION
**Pull request by BrechtDeVlieger**
Asynctest calls asyncio.SafeChildWatcher() if a process is launched during a test.

### CODE REVIEW

**Comment by nathan-hoad** [comment]
Could you expand a bit on what asynctest is for? I'm using py.test for running the tests, and I'm not seeing the necessity for this behaviour. I'd like to avoid monkey patching asyncio, particularly just for tests.

**Comment by BrechtDeVlieger** [comment]
asynctest allows to test coroutines and futures more efficiently. It automatically creates new loops for each test and handles all related resources. It also provides awaitable mocks for futures and coroutines.
http://asynctest.readthedocs.io/en/latest/index.html

But I understand that monkey patching might not be the most elegant way of doing this.

**Comment by BrechtDeVlieger** [comment]
However, the NotImplementedError which is raised when calling set_child_watcher on GLibChildWatcher should be fixed.

**Comment by nathan-hoad** [comment]
Ahh, I misunderstood the context! My apologies. I've dug into it things now and I understand what's going on :) I think that monkey patching is the most appropriate action we can take here. I can provide a real implementation of set_child_watcher as well, could you try with this patch and if it works for you, I'll put out a new release tomorrow.

```
diff --git a/gbulb/glib_events.py b/gbulb/glib_events.py
index 084e915..82cb6e3 100644
--- a/gbulb/glib_events.py
+++ b/gbulb/glib_events.py
@@ -399,7 +399,19 @@ class GLibEventLoopPolicy(events.AbstractEventLoopPolicy):
         self.set_event_loop = self._policy.set_event_loop
         self.get_child_watcher = self._policy.get_child_watcher
 
-        self._policy.set_child_watcher(GLibChildWatcher())
+        self.set_child_watcher(GLibChildWatcher())
+
+    def set_child_watcher(self, watcher):
+        """Set a child watcher.
+
+        Must be an an instance of GLibChildWatcher, as it ties in with GLib
+        appropriately.
+        """
+
+        if not isinstance(watcher, GLibChildWatcher):
+            raise TypeError("Only GLibChildWatcher is supported!")
+
+        self._policy.set_child_watcher(watcher)
 
     def new_event_loop(self):
         """Create a new event loop and return it."""
```

**Comment by BrechtDeVlieger** [comment]
Almost! One can also pass None as ChildWatcher. This is the source code of the official policy:

class _UnixDefaultEventLoopPolicy(events.BaseDefaultEventLoopPolicy):
    """UNIX event loop policy with a watcher for child processes."""
    ...
    def set_child_watcher(self, watcher):
        """Set the watcher for child processes."""

        assert watcher is None or isinstance(watcher, AbstractChildWatcher)

        if self._watcher is not None:
            self._watcher.close()

        self._watcher = watcher

**Pull request closed without merging**
